version: '3'
services:
  maplestory:
    network_mode: "host"
    build: .
    depends_on:
      - db
    environment:
      WAIT_HOSTS: localhost:3306
    ports:
      - "7575:7575"  # Map container's port 7575 to host's port 7575
      - "7576:7576"  # Map container's port 7576 to host's port 7576
      - "7577:7577"  # Map container's port 7577 to host's port 7577
      - "8484:8484"
  db:
    network_mode: "host"
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "heavenms"
    ports:
      - "3306:3306"
    


    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: